#!/bin/bash 
if [ -z "$1" ]; then
    echo "Использование: $0 .."
    exit 1
fi
DIR="$1"
 for file in "$DIR"/*.txt; do
   
    if [ -f "$file" ]; then
        while IFS= read -r line; do
            IFS='.' read -r name age email <<< "$line"
            echo "Имя: $name, Возраст: $age, Email: $email"
        done < "$file"
    fi
done
 
